name: Build Static ARM64 Git Binary

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            dh-autoreconf \
            libcurl4-gnutls-dev \
            libexpat1-dev \
            gettext \
            zlib1g-dev \
            libssl-dev \
            libncurses5-dev \
            git

      - name: Clone Git source
        run: |
          git clone https://github.com/git/git.git
          cd git
          make configure
          ./configure --prefix=/tmp/git-static CFLAGS="-static" LDFLAGS="-static" NO_OPENSSL=1 NO_CURL=1 NO_EXPAT=1 NO_GETTEXT=1 NO_PERL=1 NO_PYTHON=1 NO_TCLTK=1
          make -j$(nproc)
          make install

      - name: Upload static Git binary
        uses: actions/upload-artifact@v4
        with:
          name: git_static
          path: /tmp/git-static/
